# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculator.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\"#\n\x0b\x43\x61lcRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x1e\n\x0c\x43\x61lcResponse\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32Y\n\nCalculator\x12\"\n\x03\x41\x64\x64\x12\x0c.CalcRequest\x1a\r.CalcResponse\x12\'\n\x08Subtract\x12\x0c.CalcRequest\x1a\r.CalcResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CALCREQUEST']._serialized_start=20
  _globals['_CALCREQUEST']._serialized_end=55
  _globals['_CALCRESPONSE']._serialized_start=57
  _globals['_CALCRESPONSE']._serialized_end=87
  _globals['_CALCULATOR']._serialized_start=89
  _globals['_CALCULATOR']._serialized_end=178
# @@protoc_insertion_point(module_scope)
