# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator_messages.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63\x61lculator_messages.proto\x12\x12\x63\x61lculator_message\"7\n\x11\x43\x61lculatorRequest\x12\x10\n\x08operand1\x18\x01 \x01(\x01\x12\x10\n\x08operand2\x18\x02 \x01(\x01\"$\n\x12\x43\x61lculatorResponse\x12\x0e\n\x06result\x18\x01 \x01(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_messages_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CALCULATORREQUEST']._serialized_start=49
  _globals['_CALCULATORREQUEST']._serialized_end=104
  _globals['_CALCULATORRESPONSE']._serialized_start=106
  _globals['_CALCULATORRESPONSE']._serialized_end=142
# @@protoc_insertion_point(module_scope)
