# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: template_message.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16template_message.proto\x12\x10mini_rpc_message\x1a\x19google/protobuf/any.proto\"D\n\x0eMiniRpcRequest\x12\x0e\n\x06method\x18\x01 \x01(\t\x12\"\n\x04\x61rgs\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\"S\n\x0fMiniRpcResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0c\n\x04info\x18\x02 \x01(\t\x12\"\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x14.google.protobuf.Anyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'template_message_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MINIRPCREQUEST']._serialized_start=71
  _globals['_MINIRPCREQUEST']._serialized_end=139
  _globals['_MINIRPCRESPONSE']._serialized_start=141
  _globals['_MINIRPCRESPONSE']._serialized_end=224
# @@protoc_insertion_point(module_scope)
